// @generated by protoc-gen-es v2.6.0 with parameter "target=ts"
// @generated from file canvas.proto (package com.spotify.canvazcache, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file canvas.proto.
 */
export const file_canvas: GenFile = /*@__PURE__*/
  fileDesc("CgxjYW52YXMucHJvdG8SF2NvbS5zcG90aWZ5LmNhbnZhemNhY2hlIjMKBkFydGlzdBILCgN1cmkYASABKAkSDAoEbmFtZRgCIAEoCRIOCgZhdmF0YXIYAyABKAki6wIKDkNhbnZhc1Jlc3BvbnNlEkAKCGNhbnZhc2VzGAEgAygLMi4uY29tLnNwb3RpZnkuY2FudmF6Y2FjaGUuQ2FudmFzUmVzcG9uc2UuQ2FudmFzEhYKDnR0bF9pbl9zZWNvbmRzGAIgASgDGv4BCgZDYW52YXMSCgoCaWQYASABKAkSCwoDdXJsGAIgASgJEg4KBmZpbGVJRBgDIAEoCRIrCgR0eXBlGAQgASgOMh0uY29tLnNwb3RpZnkuY2FudmF6Y2FjaGUuVHlwZRIQCgh0cmFja1VSSRgFIAEoCRIvCgZhcnRpc3QYBiABKAsyHy5jb20uc3BvdGlmeS5jYW52YXpjYWNoZS5BcnRpc3QSEAoIZXhwbGljaXQYByABKAgSEgoKdXBsb2FkZWRCeRgIIAEoCRIMCgRldGFnGAkgASgJEhEKCWNhbnZhc1VSSRgLIAEoCRIUCgxzdG9yeWxpbmVzSUQYDCABKAkidwoNQ2FudmFzUmVxdWVzdBI8CgZ0cmFja3MYASADKAsyLC5jb20uc3BvdGlmeS5jYW52YXpjYWNoZS5DYW52YXNSZXF1ZXN0LlRyYWNrGigKBVRyYWNrEhEKCXRyYWNrX3VyaRgBIAEoCRIMCgRldGFnGAIgASgJKlIKBFR5cGUSCQoFSU1BR0UQABIJCgVWSURFTxABEhEKDVZJREVPX0xPT1BJTkcQAhIYChRWSURFT19MT09QSU5HX1JBTkRPTRADEgcKA0dJRhAEQhYKEmNvbS5zcG90aWZ5LmNhbnZhekgCYgZwcm90bzM");

/**
 * @generated from message com.spotify.canvazcache.Artist
 */
export type Artist = Message<"com.spotify.canvazcache.Artist"> & {
  /**
   * @generated from field: string uri = 1;
   */
  uri: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: string avatar = 3;
   */
  avatar: string;
};

/**
 * Describes the message com.spotify.canvazcache.Artist.
 * Use `create(ArtistSchema)` to create a new message.
 */
export const ArtistSchema: GenMessage<Artist> = /*@__PURE__*/
  messageDesc(file_canvas, 0);

/**
 * @generated from message com.spotify.canvazcache.CanvasResponse
 */
export type CanvasResponse = Message<"com.spotify.canvazcache.CanvasResponse"> & {
  /**
   * @generated from field: repeated com.spotify.canvazcache.CanvasResponse.Canvas canvases = 1;
   */
  canvases: CanvasResponse_Canvas[];

  /**
   * @generated from field: int64 ttl_in_seconds = 2;
   */
  ttlInSeconds: bigint;
};

/**
 * Describes the message com.spotify.canvazcache.CanvasResponse.
 * Use `create(CanvasResponseSchema)` to create a new message.
 */
export const CanvasResponseSchema: GenMessage<CanvasResponse> = /*@__PURE__*/
  messageDesc(file_canvas, 1);

/**
 * @generated from message com.spotify.canvazcache.CanvasResponse.Canvas
 */
export type CanvasResponse_Canvas = Message<"com.spotify.canvazcache.CanvasResponse.Canvas"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string url = 2;
   */
  url: string;

  /**
   * @generated from field: string fileID = 3;
   */
  fileID: string;

  /**
   * @generated from field: com.spotify.canvazcache.Type type = 4;
   */
  type: Type;

  /**
   * @generated from field: string trackURI = 5;
   */
  trackURI: string;

  /**
   * @generated from field: com.spotify.canvazcache.Artist artist = 6;
   */
  artist?: Artist;

  /**
   * @generated from field: bool explicit = 7;
   */
  explicit: boolean;

  /**
   * @generated from field: string uploadedBy = 8;
   */
  uploadedBy: string;

  /**
   * @generated from field: string etag = 9;
   */
  etag: string;

  /**
   * @generated from field: string canvasURI = 11;
   */
  canvasURI: string;

  /**
   * @generated from field: string storylinesID = 12;
   */
  storylinesID: string;
};

/**
 * Describes the message com.spotify.canvazcache.CanvasResponse.Canvas.
 * Use `create(CanvasResponse_CanvasSchema)` to create a new message.
 */
export const CanvasResponse_CanvasSchema: GenMessage<CanvasResponse_Canvas> = /*@__PURE__*/
  messageDesc(file_canvas, 1, 0);

/**
 * @generated from message com.spotify.canvazcache.CanvasRequest
 */
export type CanvasRequest = Message<"com.spotify.canvazcache.CanvasRequest"> & {
  /**
   * @generated from field: repeated com.spotify.canvazcache.CanvasRequest.Track tracks = 1;
   */
  tracks: CanvasRequest_Track[];
};

/**
 * Describes the message com.spotify.canvazcache.CanvasRequest.
 * Use `create(CanvasRequestSchema)` to create a new message.
 */
export const CanvasRequestSchema: GenMessage<CanvasRequest> = /*@__PURE__*/
  messageDesc(file_canvas, 2);

/**
 * @generated from message com.spotify.canvazcache.CanvasRequest.Track
 */
export type CanvasRequest_Track = Message<"com.spotify.canvazcache.CanvasRequest.Track"> & {
  /**
   * @generated from field: string track_uri = 1;
   */
  trackUri: string;

  /**
   * @generated from field: string etag = 2;
   */
  etag: string;
};

/**
 * Describes the message com.spotify.canvazcache.CanvasRequest.Track.
 * Use `create(CanvasRequest_TrackSchema)` to create a new message.
 */
export const CanvasRequest_TrackSchema: GenMessage<CanvasRequest_Track> = /*@__PURE__*/
  messageDesc(file_canvas, 2, 0);

/**
 * @generated from enum com.spotify.canvazcache.Type
 */
export enum Type {
  /**
   * @generated from enum value: IMAGE = 0;
   */
  IMAGE = 0,

  /**
   * @generated from enum value: VIDEO = 1;
   */
  VIDEO = 1,

  /**
   * @generated from enum value: VIDEO_LOOPING = 2;
   */
  VIDEO_LOOPING = 2,

  /**
   * @generated from enum value: VIDEO_LOOPING_RANDOM = 3;
   */
  VIDEO_LOOPING_RANDOM = 3,

  /**
   * @generated from enum value: GIF = 4;
   */
  GIF = 4,
}

/**
 * Describes the enum com.spotify.canvazcache.Type.
 */
export const TypeSchema: GenEnum<Type> = /*@__PURE__*/
  enumDesc(file_canvas, 0);

